spring:
  h2:
    console:
      enabled: false
      path: "/h2"
  datasource:
    url: jdbc:postgresql://postgres-service:5432/ordermanager
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
logging:
  file:
    path: ./
    name: ordermanager.log
