spring:
  h2:
    console:
      enabled: false
      path: "/h2"
  datasource:
    url: jdbc:h2:file:./ordermanager-db
    username: foo
    password: bar
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 80
#    show-sql: true