apiVersion: v1
kind: ConfigMap
metadata:
  name: order-manager-config
data:
  application.yaml: |
    ---
    # this application.yaml is used to start the container
    spring:
      h2:
        console:
          enabled: false
          path: "/h2"
      datasource:
        url: jdbc:h2:file:./ordermanager-db
        username: foo
        password: bar
        driver-class-name: org.h2.Driver
      flyway:
        locations: classpath:db/migration/common,classpath:db/migration/h2
      jpa:
        hibernate:
          ddl-auto: none
    logging:
      file:
        path: ./
        name: ordermanager.log
    ---
    spring:
    datasource:
      url: jdbc:postgresql://postgres-service:5432/ordermanager
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
    flyway:
      locations: classpath:db/migration/common,classpath:db/migration/postgres
