apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-app
          image: postgres:14.2-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: "/postgresdata"
              name: postgres-pv-storage
      volumes:
          - name: postgres-pv-storage
            persistentVolumeClaim:
              claimName: postgres-pv-claim
